{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8fd7de0e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "=============================================================================\n",
    "FITBIT HEALTH DATA - COMPLETE ANALYSIS PIPELINE v2\n",
    "=============================================================================\n",
    "Quy trình: Data Merging → Clean Data → EDA → RFM Scoring → Churn Prediction\n",
    "FIX: Windows path + tất cả file nằm trong 1 thư mục gốc (flat structure)\n",
    "=============================================================================\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import warnings\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from datetime import datetime, timedelta\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import (classification_report, roc_auc_score,\n",
    "                             roc_curve, ConfusionMatrixDisplay)\n",
    "import joblib\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "pd.set_option(\"display.max_columns\", None)\n",
    "pd.set_option(\"display.float_format\", \"{:.2f}\".format)\n",
    "\n",
    "# =============================================================================\n",
    "# ★ CHỈ CẦN THAY ĐỔI DÒNG NÀY ★\n",
    "# Dùng r\"...\" (raw string) để tránh lỗi unicode escape trên Windows\n",
    "# =============================================================================\n",
    "BASE_PATH = r\"C:\\Users\\USER\\Downloads\\archive\\mturkfitbit_export_4.12.16-5.12.16\\Fitabase Data 4.12.16-5.12.16\"\n",
    "\n",
    "# Tất cả file CSV nằm thẳng trong BASE_PATH (không cần subfolder)\n",
    "def p(filename):\n",
    "    \"\"\"Trả về đường dẫn đầy đủ tới file CSV.\"\"\"\n",
    "    return os.path.join(BASE_PATH, filename)\n",
    "\n",
    "OUTPUT_DIR = os.path.join(BASE_PATH, \"output_analysis\")\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "\n",
    "# Màu sắc\n",
    "PALETTE = [\"#2196F3\", \"#4CAF50\", \"#FF9800\", \"#E91E63\", \"#9C27B0\"]\n",
    "plt.rcParams.update({\n",
    "    \"figure.facecolor\": \"white\",\n",
    "    \"axes.facecolor\":   \"#F8F9FA\",\n",
    "    \"axes.grid\":        True,\n",
    "    \"grid.alpha\":       0.4,\n",
    "    \"font.size\":        11,\n",
    "})\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# HELPER\n",
    "# =============================================================================\n",
    "def load_csv(filename, date_cols=None):\n",
    "    \"\"\"Đọc CSV từ BASE_PATH, parse ngày, fill NA → 0.\"\"\"\n",
    "    filepath = p(filename)\n",
    "    if not os.path.exists(filepath):\n",
    "        print(f\"   ⚠ Không tìm thấy file: {filename} — bỏ qua\")\n",
    "        return None\n",
    "    df = pd.read_csv(filepath, parse_dates=date_cols if date_cols else False)\n",
    "    df.fillna(0, inplace=True)\n",
    "    return df\n",
    "\n",
    "\n",
    "def std_id(df, id_col=\"Id\"):\n",
    "    df[id_col] = df[id_col].astype(str)\n",
    "    return df\n",
    "\n",
    "\n",
    "def to_date(df, col):\n",
    "    df[col] = pd.to_datetime(df[col], errors=\"coerce\").dt.date\n",
    "    return df\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# BƯỚC 1: ĐỌC VÀ GỘP DỮ LIỆU\n",
    "# =============================================================================\n",
    "def merge_daily():\n",
    "    print(\"\\n[1/5] Gộp dữ liệu hàng ngày...\")\n",
    "\n",
    "    activity    = load_csv(\"dailyActivity_merged.csv\",    [\"ActivityDate\"])\n",
    "    calories    = load_csv(\"dailyCalories_merged.csv\",    [\"ActivityDay\"])\n",
    "    intensities = load_csv(\"dailyIntensities_merged.csv\", [\"ActivityDay\"])\n",
    "    steps       = load_csv(\"dailySteps_merged.csv\",       [\"ActivityDay\"])\n",
    "\n",
    "    for df in [activity, calories, intensities, steps]:\n",
    "        std_id(df)\n",
    "\n",
    "    to_date(activity, \"ActivityDate\");    activity.rename(columns={\"ActivityDate\": \"Date\"}, inplace=True)\n",
    "    to_date(calories, \"ActivityDay\");     calories.rename(columns={\"ActivityDay\": \"Date\", \"Calories\": \"Cal_daily\"}, inplace=True)\n",
    "    to_date(intensities, \"ActivityDay\");  intensities.rename(columns={\"ActivityDay\": \"Date\"}, inplace=True)\n",
    "    to_date(steps, \"ActivityDay\");        steps.rename(columns={\"ActivityDay\": \"Date\", \"StepTotal\": \"StepTotal_daily\"}, inplace=True)\n",
    "\n",
    "    daily = activity.copy()\n",
    "    for right in [calories, intensities, steps]:\n",
    "        daily = daily.merge(right, on=[\"Id\", \"Date\"], how=\"outer\", suffixes=(\"\", \"_dup\"))\n",
    "        dup_cols = [c for c in daily.columns if c.endswith(\"_dup\")]\n",
    "        daily.drop(columns=dup_cols, inplace=True)\n",
    "\n",
    "    daily.fillna(0, inplace=True)\n",
    "    print(f\"   ✓ {daily.shape[0]:,} dòng | {daily.shape[1]} cột | {daily['Id'].nunique()} người dùng\")\n",
    "    return daily\n",
    "\n",
    "\n",
    "def merge_sleep():\n",
    "    print(\"[2/5] Gộp dữ liệu giấc ngủ...\")\n",
    "\n",
    "    sleep_day = load_csv(\"sleepDay_merged.csv\", [\"SleepDay\"])\n",
    "    if sleep_day is not None:\n",
    "        std_id(sleep_day)\n",
    "        to_date(sleep_day, \"SleepDay\")\n",
    "        sleep_day.rename(columns={\"SleepDay\": \"Date\"}, inplace=True)\n",
    "\n",
    "    minute_sleep = load_csv(\"minuteSleep_merged.csv\", [\"date\"])\n",
    "    ms_agg = None\n",
    "    if minute_sleep is not None:\n",
    "        std_id(minute_sleep)\n",
    "        to_date(minute_sleep, \"date\")\n",
    "        ms_agg = minute_sleep.groupby([\"Id\", \"date\"]).agg(\n",
    "            MinuteSleep_count    =(\"value\", \"count\"),\n",
    "            MinuteSleep_avgValue =(\"value\", \"mean\")\n",
    "        ).reset_index().rename(columns={\"date\": \"Date\"})\n",
    "\n",
    "    if sleep_day is not None and ms_agg is not None:\n",
    "        sleep = sleep_day.merge(ms_agg, on=[\"Id\", \"Date\"], how=\"outer\")\n",
    "    elif sleep_day is not None:\n",
    "        sleep = sleep_day\n",
    "    else:\n",
    "        sleep = ms_agg\n",
    "\n",
    "    sleep.fillna(0, inplace=True)\n",
    "    print(f\"   ✓ {sleep.shape[0]:,} dòng | {sleep.shape[1]} cột\")\n",
    "    return sleep\n",
    "\n",
    "\n",
    "def merge_cardio():\n",
    "    print(\"[3/5] Gộp dữ liệu tim mạch...\")\n",
    "\n",
    "    def load_hourly(filename, value_cols, agg_names):\n",
    "        df = load_csv(filename, [\"ActivityHour\"])\n",
    "        if df is None:\n",
    "            return None\n",
    "        std_id(df)\n",
    "        df[\"Date\"] = pd.to_datetime(df[\"ActivityHour\"], errors=\"coerce\").dt.date\n",
    "        return df.groupby([\"Id\", \"Date\"])[value_cols].agg([\"sum\", \"mean\"]) \\\n",
    "                 .set_axis([f\"{n}_{a}\" for n in agg_names for a in [\"sum\",\"mean\"]], axis=1) \\\n",
    "                 .reset_index()\n",
    "\n",
    "    cal_agg = load_csv(\"hourlyCalories_merged.csv\", [\"ActivityHour\"])\n",
    "    if cal_agg is not None:\n",
    "        std_id(cal_agg)\n",
    "        cal_agg[\"Date\"] = pd.to_datetime(cal_agg[\"ActivityHour\"], errors=\"coerce\").dt.date\n",
    "        cal_agg = cal_agg.groupby([\"Id\",\"Date\"]).agg(\n",
    "            HourlyCalories_sum=(\"Calories\",\"sum\"), HourlyCalories_mean=(\"Calories\",\"mean\")\n",
    "        ).reset_index()\n",
    "\n",
    "    int_agg = load_csv(\"hourlyIntensities_merged.csv\", [\"ActivityHour\"])\n",
    "    if int_agg is not None:\n",
    "        std_id(int_agg)\n",
    "        int_agg[\"Date\"] = pd.to_datetime(int_agg[\"ActivityHour\"], errors=\"coerce\").dt.date\n",
    "        int_agg = int_agg.groupby([\"Id\",\"Date\"]).agg(\n",
    "            HourlyIntensity_sum=(\"TotalIntensity\",\"sum\"),\n",
    "            HourlyIntensity_mean=(\"TotalIntensity\",\"mean\"),\n",
    "        ).reset_index()\n",
    "\n",
    "    stp_agg = load_csv(\"hourlySteps_merged.csv\", [\"ActivityHour\"])\n",
    "    if stp_agg is not None:\n",
    "        std_id(stp_agg)\n",
    "        stp_agg[\"Date\"] = pd.to_datetime(stp_agg[\"ActivityHour\"], errors=\"coerce\").dt.date\n",
    "        stp_agg = stp_agg.groupby([\"Id\",\"Date\"]).agg(\n",
    "            HourlySteps_sum=(\"StepTotal\",\"sum\"), HourlySteps_mean=(\"StepTotal\",\"mean\")\n",
    "        ).reset_index()\n",
    "\n",
    "    hr = load_csv(\"heartrate_seconds_merged.csv\", [\"Time\"])\n",
    "    hr_agg = None\n",
    "    if hr is not None:\n",
    "        std_id(hr)\n",
    "        hr[\"Date\"] = pd.to_datetime(hr[\"Time\"], errors=\"coerce\").dt.date\n",
    "        hr_agg = hr.groupby([\"Id\",\"Date\"]).agg(\n",
    "            HeartRate_mean=(\"Value\",\"mean\"), HeartRate_min=(\"Value\",\"min\"),\n",
    "            HeartRate_max=(\"Value\",\"max\"),  HeartRate_std=(\"Value\",\"std\")\n",
    "        ).reset_index()\n",
    "\n",
    "    dfs = [d for d in [cal_agg, int_agg, stp_agg, hr_agg] if d is not None]\n",
    "    cardio = dfs[0]\n",
    "    for d in dfs[1:]:\n",
    "        cardio = cardio.merge(d, on=[\"Id\",\"Date\"], how=\"outer\")\n",
    "    cardio.fillna(0, inplace=True)\n",
    "    print(f\"   ✓ {cardio.shape[0]:,} dòng | {cardio.shape[1]} cột\")\n",
    "    return cardio\n",
    "\n",
    "\n",
    "def merge_additional():\n",
    "    print(\"[4/5] Gộp dữ liệu bổ sung...\")\n",
    "\n",
    "    weight = load_csv(\"weightLogInfo_merged.csv\", [\"Date\"])\n",
    "    weight_agg = None\n",
    "    if weight is not None:\n",
    "        std_id(weight)\n",
    "        to_date(weight, \"Date\")\n",
    "        weight_agg = weight.groupby(\"Id\").agg(\n",
    "            Weight_mean=(\"WeightKg\",\"mean\"), BMI_mean=(\"BMI\",\"mean\"),\n",
    "            Weight_records=(\"WeightKg\",\"count\")\n",
    "        ).reset_index()\n",
    "\n",
    "    mets = load_csv(\"minuteMETsNarrow_merged.csv\", [\"ActivityMinute\"])\n",
    "    mets_agg = None\n",
    "    if mets is not None:\n",
    "        std_id(mets)\n",
    "        mets[\"Date\"] = pd.to_datetime(mets[\"ActivityMinute\"], errors=\"coerce\").dt.date\n",
    "        mets_agg = mets.groupby([\"Id\",\"Date\"]).agg(\n",
    "            METs_mean=(\"METs\",\"mean\"), METs_sum=(\"METs\",\"sum\")\n",
    "        ).reset_index()\n",
    "\n",
    "    print(f\"   ✓ Weight: {len(weight_agg) if weight_agg is not None else 0} users | METs: {len(mets_agg) if mets_agg is not None else 0} dòng\")\n",
    "    return weight_agg, mets_agg\n",
    "\n",
    "\n",
    "def build_master(daily, sleep, cardio, weight_agg, mets_agg):\n",
    "    print(\"[5/5] Xây dựng master dataset...\")\n",
    "\n",
    "    master = daily.merge(sleep,  on=[\"Id\",\"Date\"], how=\"outer\", suffixes=(\"\",\"_sleep\"))\n",
    "    master = master.merge(cardio, on=[\"Id\",\"Date\"], how=\"outer\", suffixes=(\"\",\"_cardio\"))\n",
    "    if mets_agg is not None:\n",
    "        master = master.merge(mets_agg, on=[\"Id\",\"Date\"], how=\"outer\")\n",
    "    if weight_agg is not None:\n",
    "        master = master.merge(weight_agg, on=\"Id\", how=\"left\")\n",
    "\n",
    "    master.fillna(0, inplace=True)\n",
    "    master[\"Date\"] = pd.to_datetime(master[\"Date\"])\n",
    "    master.sort_values([\"Id\",\"Date\"], inplace=True)\n",
    "    master.reset_index(drop=True, inplace=True)\n",
    "    print(f\"   ✓ Master: {master.shape[0]:,} dòng | {master.shape[1]} cột | {master['Id'].nunique()} users\")\n",
    "    return master\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# BƯỚC 2: CLEAN DATA\n",
    "# =============================================================================\n",
    "def clean_data(df):\n",
    "    print(\"\\n━━━━ CLEAN DATA ━━━━\")\n",
    "    before = df.shape\n",
    "\n",
    "    df.drop_duplicates(subset=[\"Id\",\"Date\"], inplace=True)\n",
    "    df = df[df[\"Id\"].astype(str).str.strip() != \"0\"]\n",
    "\n",
    "    rules = {\n",
    "        \"TotalSteps\":        (0, 100_000),\n",
    "        \"Calories\":          (0, 10_000),\n",
    "        \"TotalDistance\":     (0, 200),\n",
    "        \"VeryActiveMinutes\": (0, 1440),\n",
    "        \"SedentaryMinutes\":  (0, 1440),\n",
    "        \"TotalMinutesAsleep\":(0, 1440),\n",
    "        \"HeartRate_mean\":    (30, 220),\n",
    "        \"BMI_mean\":          (10, 70),\n",
    "    }\n",
    "    for col, (lo, hi) in rules.items():\n",
    "        if col in df.columns:\n",
    "            df[col] = df[col].clip(lower=lo, upper=hi)\n",
    "\n",
    "    df.fillna(0, inplace=True)\n",
    "    print(f\"   Trước: {before} → Sau: {df.shape}\")\n",
    "    print(f\"   Users: {df['Id'].nunique()} | Ngày: {df['Date'].min().date()} → {df['Date'].max().date()}\")\n",
    "    return df.reset_index(drop=True)\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# BƯỚC 3: EDA\n",
    "# =============================================================================\n",
    "def eda(df):\n",
    "    print(\"\\n━━━━ EDA ━━━━\")\n",
    "\n",
    "    # Thống kê mô tả\n",
    "    df.select_dtypes(include=\"number\").describe().T \\\n",
    "      .to_csv(os.path.join(OUTPUT_DIR, \"01_descriptive_stats.csv\"))\n",
    "    print(\"   ✓ 01_descriptive_stats.csv\")\n",
    "\n",
    "    # Phân phối chỉ số chính\n",
    "    key_cols = [c for c in [\"TotalSteps\",\"Calories\",\"TotalMinutesAsleep\",\n",
    "                             \"VeryActiveMinutes\",\"SedentaryMinutes\",\"HeartRate_mean\"]\n",
    "                if c in df.columns]\n",
    "    fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n",
    "    fig.suptitle(\"Phân phối các chỉ số sức khỏe chính\", fontsize=16, fontweight=\"bold\")\n",
    "    for ax, col in zip(axes.flatten(), key_cols):\n",
    "        data = df[df[col] > 0][col]\n",
    "        ax.hist(data, bins=40, color=PALETTE[0], alpha=0.8, edgecolor=\"white\")\n",
    "        ax.axvline(data.mean(),   color=PALETTE[3], ls=\"--\", lw=2, label=f\"Mean: {data.mean():.0f}\")\n",
    "        ax.axvline(data.median(), color=PALETTE[2], ls=\"--\", lw=2, label=f\"Median: {data.median():.0f}\")\n",
    "        ax.set_title(col, fontweight=\"bold\"); ax.legend(fontsize=9)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"02_distributions.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 02_distributions.png\")\n",
    "\n",
    "    # Xu hướng thời gian\n",
    "    trend_cols = [c for c in [\"TotalSteps\",\"Calories\",\"TotalMinutesAsleep\"] if c in df.columns]\n",
    "    daily_trend = df.groupby(\"Date\")[trend_cols].mean()\n",
    "    fig, axes = plt.subplots(len(trend_cols), 1, figsize=(16, 4*len(trend_cols)), sharex=True)\n",
    "    fig.suptitle(\"Xu hướng theo thời gian\", fontsize=15, fontweight=\"bold\")\n",
    "    if len(trend_cols) == 1: axes = [axes]\n",
    "    for ax, col, color in zip(axes, trend_cols, PALETTE):\n",
    "        ax.plot(daily_trend.index, daily_trend[col], color=color, lw=2)\n",
    "        ax.fill_between(daily_trend.index, daily_trend[col], alpha=0.15, color=color)\n",
    "        ax.set_ylabel(col, fontweight=\"bold\")\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"03_time_trends.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 03_time_trends.png\")\n",
    "\n",
    "    # Correlation heatmap\n",
    "    corr_cols = [c for c in [\"TotalSteps\",\"Calories\",\"TotalDistance\",\"VeryActiveMinutes\",\n",
    "                              \"FairlyActiveMinutes\",\"SedentaryMinutes\",\"TotalMinutesAsleep\",\n",
    "                              \"HeartRate_mean\",\"BMI_mean\",\"METs_mean\"] if c in df.columns]\n",
    "    corr = df[corr_cols].replace(0, np.nan).dropna(thresh=3).corr()\n",
    "    fig, ax = plt.subplots(figsize=(14, 11))\n",
    "    sns.heatmap(corr, mask=np.triu(np.ones_like(corr, dtype=bool)),\n",
    "                annot=True, fmt=\".2f\", cmap=\"RdYlGn\", center=0, ax=ax,\n",
    "                linewidths=0.5, annot_kws={\"size\": 9})\n",
    "    ax.set_title(\"Ma trận tương quan\", fontsize=15, fontweight=\"bold\")\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"04_correlation_heatmap.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 04_correlation_heatmap.png\")\n",
    "\n",
    "    # Bước chân theo ngày trong tuần\n",
    "    df2 = df.copy()\n",
    "    df2[\"Weekday\"] = pd.to_datetime(df2[\"Date\"]).dt.dayofweek\n",
    "    weekday_vi = [\"Thứ 2\",\"Thứ 3\",\"Thứ 4\",\"Thứ 5\",\"Thứ 6\",\"Thứ 7\",\"Chủ nhật\"]\n",
    "    wsteps = df2[df2[\"TotalSteps\"]>0].groupby(\"Weekday\")[\"TotalSteps\"].mean().reindex(range(7))\n",
    "    fig, ax = plt.subplots(figsize=(12, 5))\n",
    "    bars = ax.bar(weekday_vi, wsteps.values, color=PALETTE, edgecolor=\"white\")\n",
    "    ax.bar_label(bars, fmt=\"%.0f\", padding=3, fontsize=10)\n",
    "    ax.set_title(\"Số bước chân trung bình theo ngày trong tuần\", fontsize=14, fontweight=\"bold\")\n",
    "    ax.set_ylim(0, wsteps.max() * 1.15)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"05_steps_by_weekday.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 05_steps_by_weekday.png\")\n",
    "\n",
    "    # Phân khúc người dùng\n",
    "    user_stats = df.groupby(\"Id\").agg(\n",
    "        avg_steps   =(\"TotalSteps\",\"mean\"),\n",
    "        avg_calories=(\"Calories\",\"mean\"),\n",
    "        avg_sleep   =(\"TotalMinutesAsleep\",\"mean\"),\n",
    "        active_days =(\"Date\",\"count\")\n",
    "    ).reset_index()\n",
    "    user_stats[\"activity_level\"] = pd.cut(\n",
    "        user_stats[\"avg_steps\"],\n",
    "        bins=[0,5000,7500,10000,float(\"inf\")],\n",
    "        labels=[\"Ít vận động\",\"Trung bình thấp\",\"Trung bình cao\",\"Rất năng động\"]\n",
    "    )\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n",
    "    user_stats[\"activity_level\"].value_counts().plot.pie(\n",
    "        ax=axes[0], autopct=\"%1.1f%%\", colors=PALETTE,\n",
    "        startangle=90, wedgeprops={\"edgecolor\":\"white\",\"linewidth\":2})\n",
    "    axes[0].set_title(\"Phân bố mức độ hoạt động\", fontweight=\"bold\"); axes[0].set_ylabel(\"\")\n",
    "    for lvl, color in zip(user_stats[\"activity_level\"].cat.categories, PALETTE):\n",
    "        sub = user_stats[user_stats[\"activity_level\"]==lvl]\n",
    "        axes[1].scatter(sub[\"avg_steps\"], sub[\"avg_calories\"],\n",
    "                        label=lvl, alpha=0.7, s=80, color=color, edgecolors=\"white\")\n",
    "    axes[1].set_xlabel(\"Bước chân TB/ngày\"); axes[1].set_ylabel(\"Calo TB/ngày\")\n",
    "    axes[1].set_title(\"Bước chân vs Calo\", fontweight=\"bold\"); axes[1].legend()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"06_user_segments.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 06_user_segments.png\")\n",
    "\n",
    "    return user_stats\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# BƯỚC 4: RFM SCORING\n",
    "# =============================================================================\n",
    "def rfm_scoring(df):\n",
    "    print(\"\\n━━━━ RFM SCORING ━━━━\")\n",
    "    snapshot = df[\"Date\"].max() + timedelta(days=1)\n",
    "    active = df[df[\"TotalSteps\"] > 0].copy()\n",
    "\n",
    "    rfm = active.groupby(\"Id\").agg(\n",
    "        LastActivity=(\"Date\",\"max\"),\n",
    "        Frequency   =(\"Date\",\"count\"),\n",
    "        Monetary    =(\"Calories\",\"mean\")\n",
    "    ).reset_index()\n",
    "    rfm[\"Recency\"] = (snapshot - rfm[\"LastActivity\"]).dt.days\n",
    "\n",
    "    for col, labels, ascending in [\n",
    "        (\"Recency\",   [5,4,3,2,1], True),   # ít ngày = tốt hơn\n",
    "        (\"Frequency\", [1,2,3,4,5], False),\n",
    "        (\"Monetary\",  [1,2,3,4,5], False),\n",
    "    ]:\n",
    "        score_col = col[0] + \"_score\"\n",
    "        try:\n",
    "            rfm[score_col] = pd.qcut(rfm[col], q=5, labels=labels, duplicates=\"drop\").astype(int)\n",
    "        except Exception:\n",
    "            rfm[score_col] = 3  # fallback nếu không đủ dữ liệu\n",
    "\n",
    "    rfm[\"RFM_Score\"] = rfm[\"R_score\"] + rfm[\"F_score\"] + rfm[\"M_score\"]\n",
    "\n",
    "    def segment(row):\n",
    "        r, f, m = row[\"R_score\"], row[\"F_score\"], row[\"M_score\"]\n",
    "        if r>=4 and f>=4 and m>=4: return \"Champions\"\n",
    "        elif r>=3 and f>=3:        return \"Loyal Users\"\n",
    "        elif r>=4 and f<=2:        return \"New Users\"\n",
    "        elif r<=2 and f>=4:        return \"At Risk\"\n",
    "        elif r<=2 and f<=2:        return \"Lost Users\"\n",
    "        else:                      return \"Needs Attention\"\n",
    "\n",
    "    rfm[\"Segment\"] = rfm.apply(segment, axis=1)\n",
    "\n",
    "    seg_colors = {\"Champions\":\"#4CAF50\",\"Loyal Users\":\"#2196F3\",\"New Users\":\"#FF9800\",\n",
    "                  \"At Risk\":\"#FF5722\",\"Lost Users\":\"#9C27B0\",\"Needs Attention\":\"#607D8B\"}\n",
    "    seg_counts = rfm[\"Segment\"].value_counts()\n",
    "\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n",
    "    fig.suptitle(\"RFM Segmentation\", fontsize=15, fontweight=\"bold\")\n",
    "    colors_bar = [seg_colors.get(s,\"#999\") for s in seg_counts.index]\n",
    "    bars = axes[0].barh(seg_counts.index, seg_counts.values, color=colors_bar, edgecolor=\"white\")\n",
    "    axes[0].bar_label(bars, padding=3, fontsize=11, fontweight=\"bold\")\n",
    "    axes[0].set_xlabel(\"Số người dùng\"); axes[0].set_title(\"Phân khúc RFM\", fontweight=\"bold\")\n",
    "\n",
    "    seg_stats = rfm.groupby(\"Segment\").agg(\n",
    "        Recency=(\"Recency\",\"mean\"), Frequency=(\"Frequency\",\"mean\"), Monetary=(\"Monetary\",\"mean\")\n",
    "    ).reset_index()\n",
    "    x = np.arange(len(seg_stats)); w = 0.25\n",
    "    axes[1].bar(x-w, seg_stats[\"Recency\"],       w, label=\"Recency (ngày)\",   color=PALETTE[3], alpha=0.85)\n",
    "    axes[1].bar(x,   seg_stats[\"Frequency\"],      w, label=\"Frequency (ngày)\", color=PALETTE[0], alpha=0.85)\n",
    "    axes[1].bar(x+w, seg_stats[\"Monetary\"]/100,  w, label=\"Monetary (/100)\",   color=PALETTE[1], alpha=0.85)\n",
    "    axes[1].set_xticks(x); axes[1].set_xticklabels(seg_stats[\"Segment\"], rotation=20, ha=\"right\")\n",
    "    axes[1].set_title(\"RFM trung bình theo phân khúc\", fontweight=\"bold\"); axes[1].legend()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"07_rfm_segments.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close()\n",
    "\n",
    "    rfm.to_csv(os.path.join(OUTPUT_DIR, \"rfm_results.csv\"), index=False)\n",
    "    print(\"   ✓ rfm_results.csv & 07_rfm_segments.png\")\n",
    "    print(f\"\\n{rfm['Segment'].value_counts().to_string()}\")\n",
    "    return rfm\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# BƯỚC 5: CHURN PREDICTION\n",
    "# =============================================================================\n",
    "def churn_prediction(df, rfm):\n",
    "    print(\"\\n━━━━ CHURN PREDICTION ━━━━\")\n",
    "    max_date     = df[\"Date\"].max()\n",
    "    churn_cutoff = max_date - timedelta(days=7)\n",
    "\n",
    "    last_active = df[df[\"TotalSteps\"]>0].groupby(\"Id\")[\"Date\"].max().reset_index()\n",
    "    last_active.columns = [\"Id\",\"LastActive\"]\n",
    "    last_active[\"Churn\"] = (last_active[\"LastActive\"] < churn_cutoff).astype(int)\n",
    "\n",
    "    train_df = df[df[\"Date\"] <= churn_cutoff].copy()\n",
    "    feat_agg = train_df.groupby(\"Id\").agg(\n",
    "        avg_steps         =(\"TotalSteps\",\"mean\"),\n",
    "        std_steps         =(\"TotalSteps\",\"std\"),\n",
    "        avg_calories      =(\"Calories\",\"mean\"),\n",
    "        avg_sleep         =(\"TotalMinutesAsleep\",\"mean\"),\n",
    "        avg_very_active   =(\"VeryActiveMinutes\",\"mean\"),\n",
    "        avg_sedentary     =(\"SedentaryMinutes\",\"mean\"),\n",
    "        avg_heart_rate    =(\"HeartRate_mean\",\"mean\"),\n",
    "        avg_mets          =(\"METs_mean\",\"mean\"),\n",
    "        total_active_days =(\"TotalSteps\", lambda x: (x>0).sum()),\n",
    "        total_days        =(\"Date\",\"count\"),\n",
    "        bmi               =(\"BMI_mean\",\"mean\"),\n",
    "    ).reset_index()\n",
    "\n",
    "    feat_agg[\"active_ratio\"]  = feat_agg[\"total_active_days\"] / (feat_agg[\"total_days\"] + 1)\n",
    "    feat_agg[\"step_per_calo\"] = feat_agg[\"avg_steps\"] / (feat_agg[\"avg_calories\"] + 1)\n",
    "    feat_agg.fillna(0, inplace=True)\n",
    "\n",
    "    rfm_feats = rfm[[\"Id\",\"R_score\",\"F_score\",\"M_score\",\"RFM_Score\"]].copy()\n",
    "    features  = feat_agg.merge(rfm_feats, on=\"Id\", how=\"left\").fillna(0)\n",
    "    features  = features.merge(last_active[[\"Id\",\"Churn\"]], on=\"Id\", how=\"inner\")\n",
    "\n",
    "    feat_cols = [c for c in features.columns if c not in [\"Id\",\"Churn\"]]\n",
    "    X = features[feat_cols].values\n",
    "    y = features[\"Churn\"].values\n",
    "    print(f\"   Users: {len(y)} | Churn: {y.sum()} ({y.mean()*100:.1f}%)\")\n",
    "\n",
    "    stratify_y = y if y.sum() >= 4 and (len(y)-y.sum()) >= 4 else None\n",
    "    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.25, random_state=42, stratify=stratify_y)\n",
    "    scaler = StandardScaler()\n",
    "    X_tr_s = scaler.fit_transform(X_tr)\n",
    "    X_te_s = scaler.transform(X_te)\n",
    "\n",
    "    models = {\n",
    "        \"Logistic Regression\": LogisticRegression(max_iter=1000, random_state=42),\n",
    "        \"Random Forest\":       RandomForestClassifier(n_estimators=200, random_state=42),\n",
    "        \"Gradient Boosting\":   GradientBoostingClassifier(n_estimators=200, random_state=42),\n",
    "    }\n",
    "\n",
    "    results = {}\n",
    "    fig, axes = plt.subplots(1, 3, figsize=(18, 6))\n",
    "    fig.suptitle(\"Churn Prediction - Confusion Matrix\", fontsize=15, fontweight=\"bold\")\n",
    "\n",
    "    for ax, (name, model) in zip(axes, models.items()):\n",
    "        model.fit(X_tr_s, y_tr)\n",
    "        y_pred  = model.predict(X_te_s)\n",
    "        y_proba = model.predict_proba(X_te_s)[:,1]\n",
    "        auc = roc_auc_score(y_te, y_proba) if len(np.unique(y_te))>1 else 0.5\n",
    "        results[name] = {\"model\":model,\"auc\":auc,\"y_pred\":y_pred,\"y_proba\":y_proba}\n",
    "        ConfusionMatrixDisplay.from_predictions(\n",
    "            y_te, y_pred, ax=ax, colorbar=False,\n",
    "            display_labels=[\"Không Churn\",\"Churn\"], cmap=\"Blues\")\n",
    "        ax.set_title(f\"{name}\\nAUC={auc:.3f}\", fontweight=\"bold\")\n",
    "        print(f\"\\n   [{name}] AUC={auc:.3f}\")\n",
    "        print(classification_report(y_te, y_pred, target_names=[\"Không Churn\",\"Churn\"], zero_division=0))\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"08_churn_confusion.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 08_churn_confusion.png\")\n",
    "\n",
    "    # ROC\n",
    "    fig, ax = plt.subplots(figsize=(9, 7))\n",
    "    ax.plot([0,1],[0,1],\"k--\",alpha=0.5,label=\"Random\")\n",
    "    for (name, res), color in zip(results.items(), PALETTE):\n",
    "        if len(np.unique(y_te)) > 1:\n",
    "            fpr, tpr, _ = roc_curve(y_te, res[\"y_proba\"])\n",
    "            ax.plot(fpr, tpr, lw=2.5, color=color, label=f\"{name} (AUC={res['auc']:.3f})\")\n",
    "    ax.set_xlabel(\"FPR\"); ax.set_ylabel(\"TPR\")\n",
    "    ax.set_title(\"ROC Curves\", fontsize=14, fontweight=\"bold\"); ax.legend()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"09_roc_curves.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 09_roc_curves.png\")\n",
    "\n",
    "    # Feature importance\n",
    "    rf_model = results[\"Random Forest\"][\"model\"]\n",
    "    fi = pd.Series(rf_model.feature_importances_, index=feat_cols).sort_values(ascending=False).head(15)\n",
    "    fig, ax = plt.subplots(figsize=(12, 7))\n",
    "    fi.plot.barh(ax=ax, color=PALETTE[0], edgecolor=\"white\")\n",
    "    ax.set_title(\"Top 15 Feature Importance (Random Forest)\", fontsize=14, fontweight=\"bold\")\n",
    "    ax.invert_yaxis()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(os.path.join(OUTPUT_DIR, \"10_feature_importance.png\"), dpi=150, bbox_inches=\"tight\")\n",
    "    plt.close(); print(\"   ✓ 10_feature_importance.png\")\n",
    "\n",
    "    # Lưu dự đoán\n",
    "    X_all_s = scaler.transform(features[feat_cols].values)\n",
    "    features[\"Churn_Proba\"]     = rf_model.predict_proba(X_all_s)[:,1]\n",
    "    features[\"Churn_Predicted\"] = (features[\"Churn_Proba\"] >= 0.5).astype(int)\n",
    "    features.to_csv(os.path.join(OUTPUT_DIR, \"churn_predictions.csv\"), index=False)\n",
    "    joblib.dump(rf_model, os.path.join(OUTPUT_DIR, \"churn_model_rf.pkl\"))\n",
    "    joblib.dump(scaler,   os.path.join(OUTPUT_DIR, \"churn_scaler.pkl\"))\n",
    "    print(\"   ✓ churn_predictions.csv | churn_model_rf.pkl\")\n",
    "    return features, results\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# BƯỚC 6: TÓM TẮT\n",
    "# =============================================================================\n",
    "def summary(df, rfm, churn_df):\n",
    "    print(\"\\n━━━━ TÓM TẮT ━━━━\")\n",
    "    lines = [\n",
    "        \"=\"*65,\n",
    "        \"  FITBIT HEALTH DATA - BÁO CÁO PHÂN TÍCH\",\n",
    "        \"=\"*65,\n",
    "        f\"  Người dùng   : {df['Id'].nunique()}\",\n",
    "        f\"  Bản ghi      : {len(df):,}\",\n",
    "        f\"  Thời gian    : {df['Date'].min().date()} → {df['Date'].max().date()}\",\n",
    "        \"\",\n",
    "        \"━━ HOẠT ĐỘNG TRUNG BÌNH ━━\",\n",
    "        f\"  Bước chân/ngày : {df[df['TotalSteps']>0]['TotalSteps'].mean():.0f}\",\n",
    "        f\"  Calo/ngày      : {df[df['Calories']>0]['Calories'].mean():.0f}\",\n",
    "        f\"  Giấc ngủ/ngày  : {df[df['TotalMinutesAsleep']>0]['TotalMinutesAsleep'].mean():.0f} phút\",\n",
    "        \"\",\n",
    "        \"━━ PHÂN KHÚC RFM ━━\",\n",
    "        *[f\"  {s:<20}: {n:>3} ({n/len(rfm)*100:.1f}%)\"\n",
    "          for s, n in rfm[\"Segment\"].value_counts().items()],\n",
    "        \"\",\n",
    "        \"━━ CHURN ━━\",\n",
    "        f\"  Tỷ lệ churn thực tế  : {churn_df['Churn'].mean()*100:.1f}%\",\n",
    "        f\"  Nguy cơ cao (>=70%)  : {(churn_df['Churn_Proba']>=0.7).sum()} người\",\n",
    "        \"\",\n",
    "        f\"  📁 Output: {OUTPUT_DIR}\",\n",
    "        \"=\"*65,\n",
    "    ]\n",
    "    txt = \"\\n\".join(lines)\n",
    "    print(txt)\n",
    "    with open(os.path.join(OUTPUT_DIR, \"00_summary.txt\"), \"w\", encoding=\"utf-8\") as f:\n",
    "        f.write(txt)\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# MAIN\n",
    "# =============================================================================\n",
    "def main():\n",
    "    print(\"=\"*65)\n",
    "    print(\"  FITBIT PIPELINE: Merge → Clean → EDA → RFM → Churn\")\n",
    "    print(\"=\"*65)\n",
    "\n",
    "    daily              = merge_daily()\n",
    "    sleep              = merge_sleep()\n",
    "    cardio             = merge_cardio()\n",
    "    weight_agg, mets_agg = merge_additional()\n",
    "    master             = build_master(daily, sleep, cardio, weight_agg, mets_agg)\n",
    "    master.to_csv(os.path.join(OUTPUT_DIR, \"master_dataset.csv\"), index=False)\n",
    "    print(f\"   ✓ master_dataset.csv\")\n",
    "\n",
    "    clean  = clean_data(master)\n",
    "    user_stats = eda(clean)\n",
    "    rfm    = rfm_scoring(clean)\n",
    "    churn_df, _ = churn_prediction(clean, rfm)\n",
    "    summary(clean, rfm, churn_df)\n",
    "\n",
    "    print(f\"\\n✅ XONG! Kết quả lưu tại:\\n   {OUTPUT_DIR}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
